#ifndef NPELICAN_TYPES_GENERATED_H_
#define NPELICAN_TYPES_GENERATED_H_

// Model dimensions read from the checkpoint. nPELICAN.h guards its hand
// defaults with #ifndef, so these take precedence (NPARTICLES2 = NPARTICLES + NSPURIONS).
#define NPARTICLES 16
#define NHIDDEN 4
#define NOUT 5
#define NSPURIONS 3  // 2 beams + full-jet spurion (args.add_jet)
#define NPELICAN_JET_SPURION 1  // top gains input_t jet_input[4] -> slot 2
#define NPELICAN_HEAD 16  // args.head_hidden: 2->0 -> K ReLU -> K->NOUT head
#define N2TO0_OUT 16

// GENERATED by model_loader.py --quant. Do not hand-edit.
// Per-quantizer fixed-point types derived from the checkpoint's learned
// Brevitas scales (k = -log2(scale); I = bits - k). Accumulator / MAC types
// derived by formula from those + term counts. Phase 1: INERT include — not
// yet wired into the datapath (Phase 2 swaps usage and retires the old types).

#include "ap_fixed.h"
#include "ap_int.h"

#define NPELICAN_GENERATED_TYPES 1

// ---- Quantization-point types: ap_fixed<B, B-k, AP_RND_CONV, AP_SAT> ----
typedef ap_fixed<24, 17, AP_RND_CONV, AP_SAT> dot_t;  // input_quant (signed): scale=2^-7 (7.812500000e-03), bits=24, k=7
typedef ap_fixed<24, 6, AP_RND_CONV, AP_SAT> t2_t;  // post_agg 2->2 (signed): scale=2^-18 (3.814697266e-06), bits=24, k=18
typedef ap_fixed<24, 2, AP_RND_CONV, AP_SAT> relu_t;  // act_layer (QuantReLU) (signed): scale=2^-22 (2.384185791e-07), bits=24, k=22
typedef ap_fixed<24, 1, AP_RND_CONV, AP_SAT> t0_t;  // post_agg 2->0 (signed): scale=2^-23 (1.192092896e-07), bits=24, k=23
typedef ap_fixed<24, 3, AP_RND_CONV, AP_SAT> out_t;  // output_quant (signed): scale=2^-21 (4.768371582e-07), bits=24, k=21
#define NPELICAN_RESULT_T_GENERATED 1
typedef ap_fixed<24, 3, AP_RND_CONV, AP_SAT> result_t;  // == out_t (output_quant grid)
typedef ap_fixed<24, 2, AP_RND_CONV, AP_SAT> w1_gen_t;  // 2->2 weights (signed): scale=2^-22 (2.384185791e-07), bits=24, k=22
typedef ap_fixed<24, 4, AP_RND_CONV, AP_SAT> w2_gen_t;  // 2->0 weights (signed): scale=2^-20 (9.536743164e-07), bits=24, k=20
typedef ap_fixed<24, 3, AP_RND_CONV, AP_SAT> relu0_t;  // agg_2to0.act_layer (head QuantReLU) (signed): scale=2^-21 (4.768371582e-07), bits=24, k=21
typedef ap_fixed<24, 4, AP_RND_CONV, AP_SAT> wh_gen_t;  // head weights (signed): scale=2^-20 (9.536743164e-07), bits=24, k=20

// ---- Raw-momentum / IO interface type (input_t): operand of the dot4
//      multipliers (36x36 today) that dominate DSP. NOT a learned quantizer;
//      input_quant grids the DOTS (dot_t). I = physics |p| range (flag-
//      independent); F = ceil(log2|p|max) + dot_F + 3 so the dot4 product error
//      stays < 1/2 dot_t LSB (bit-exact dots). F tracks the dot grid, so lower
//      QAT bits -> smaller F -> narrower input_t -> cheaper dot multipliers.
//      Guard macro lets nPELICAN.h keep a hand fallback for the float path.
#define NPELICAN_INPUT_T_GENERATED 1
typedef ap_fixed<37, 14, AP_RND_CONV, AP_SAT> input_t;  // raw momenta; |p|max=5336.2 (I=14), F=23 (dot_F=7)

// ---- Float-trained biases / BatchNorm constants / normalization constants ----
// These are NOT PyTorch quantization points (PyTorch keeps them in float), so
// per CLAUDE.md/plan they are WIDENED, not snapped: their fixed-point rounding
// error must stay below half the LSB of the next real quantizer they feed.
typedef ap_fixed<50, 2, AP_RND_CONV, AP_SAT> bias1_t_gen;  // b1,b1_diag (float): F = mac2 grid w1_F+t2_F + G = 48 (G=8 guard bits); |b|max I=2
typedef ap_fixed<53, 2, AP_RND_CONV, AP_SAT> bias2_t_gen;  // b2 (float): F = mac0 grid w2_F+t0_F + G = 51 (G=8 guard bits); |b|max I=2
typedef bias1_t_gen bias_t_gen;  // legacy alias (single bias type, pre-2026-10-06)
typedef ap_fixed<51, 2, AP_RND_CONV, AP_SAT> biash_t_gen;  // b_head (float): F = head grid wh_F+relu0_F + G = 49 (G=8 guard bits); |b|max I=2
typedef ap_fixed<44, 8, AP_RND_CONV, AP_SAT> bn_t_gen;  // BN mean/scale/beta (float); |c|max=111.715 (I=8), F=36
typedef ap_fixed<42, 1, AP_RND_CONV, AP_SAT> norm_t;  // 1/N̄, 1/N̄^2 normalize-late multipliers (F=41)

// ---- Aggregation summands (unquantized BatchNorm outputs) + their accumulators.
//      AGG_F = 32 fractional bits (> the finest post-agg grid t0_F=23) so the
//      raw-sum-then-renormalize lands bit-exactly on the post-agg quantizer grid;
//      storing these on the coarse post-agg grid (e.g. t2_F) would tip the rounding.
//      Each is range-typed by its OWN BN output bound; SAT guards it. Accumulators
//      add ceil(log2(#terms)) integer headroom (H2=9 full sum, H1=5 row/trace).
typedef ap_fixed<40, 8, AP_RND_CONV, AP_SAT> bn1out_t;  // batch1 = BN1(dots); |batch1|<=123.7 (I=8), F=32
typedef ap_fixed<49, 17> acc2_t;     // jmass raw sum of bn1out_t (I(bn1out)+H2)
typedef ap_fixed<45, 13> accrow_t;   // jdotp row sums of bn1out_t (I(bn1out)+H1)
typedef ap_fixed<40, 8, AP_RND_CONV, AP_SAT> tr_t;  // Tr = BN2(relu); |Tr|<=66.6 (I=8); dump-only after #2 (BN2 folded past the 2->0 aggregation)
typedef ap_fixed<33, 11> accrelu_t;     // R full sum of relu_t Tp_q (I(relu)+H2)
typedef ap_fixed<29, 7> accrelurow_t;  // R trace, sum of relu_t Tp_q (I(relu)+H1)

// ---- MAC temporaries: I = I(weight)+I(operand)+ceil(log2(#terms)), W = I+B ----
typedef ap_fixed<51, 11> mac2_t;     // 2->2 dense: 6 w1*t2 products + b1 + b1_diag = 8 terms
// bias add for the 2->2 dense output: products accumulate in mac2_t (exact product grid);
// the float-typed bias is added ONCE here at full bias precision, then the relu quantizer rounds
#define NPELICAN_MAC2B_T_GENERATED 1
typedef ap_fixed<59, 11> mac2b_t;    // I = I(mac2_t), F = BIAS1_F = 48
typedef ap_fixed<60, 9> mac0_t;     // 2->0 dense: 2*NHIDDEN w2*t0 products + b2 = 9 terms; F = BIAS2_F = 51 (exact bias add)
typedef ap_fixed<61, 12> mach_t;     // head: K=16 wh*relu0 products + b_head = 17 terms; F = BIASH_F = 49 (exact bias add)

#endif  // NPELICAN_TYPES_GENERATED_H_
