#ifndef NPELICAN_TYPES_GENERATED_H_
#define NPELICAN_TYPES_GENERATED_H_

// Model dimensions read from the checkpoint. nPELICAN.h guards its hand
// defaults with #ifndef, so these take precedence (NPARTICLES2 = NPARTICLES + 2).
#define NPARTICLES 16
#define NHIDDEN 2
#define NOUT 5

// GENERATED by model_loader.py --quant. Do not hand-edit.
// Per-quantizer fixed-point types derived from the checkpoint's learned
// Brevitas scales (k = -log2(scale); I = bits - k). Accumulator / MAC types
// derived by formula from those + term counts. Phase 1: INERT include — not
// yet wired into the datapath (Phase 2 swaps usage and retires the old types).

#include "ap_fixed.h"
#include "ap_int.h"

#define NPELICAN_GENERATED_TYPES 1

// ---- Quantization-point types: ap_fixed<B, B-k, AP_RND_CONV, AP_SAT> ----
typedef ap_fixed<6, 13, AP_RND_CONV, AP_SAT> dot_t;  // input_quant (signed): scale=2^--7 (1.280000000e+02), bits=6, k=-7
typedef ap_fixed<6, 5, AP_RND_CONV, AP_SAT> t2_t;  // post_agg 2->2 (signed): scale=2^-1 (5.000000000e-01), bits=6, k=1
typedef ap_fixed<6, 4, AP_RND_CONV, AP_SAT> relu_t;  // act_layer (QuantReLU) (signed): scale=2^-2 (2.500000000e-01), bits=6, k=2
typedef ap_fixed<6, 1, AP_RND_CONV, AP_SAT> t0_t;  // post_agg 2->0 (signed): scale=2^-5 (3.125000000e-02), bits=6, k=5
typedef ap_fixed<6, 2, AP_RND_CONV, AP_SAT> out_t;  // output_quant (signed): scale=2^-4 (6.250000000e-02), bits=6, k=4
#define NPELICAN_RESULT_T_GENERATED 1
typedef ap_fixed<6, 2, AP_RND_CONV, AP_SAT> result_t;  // == out_t (output_quant grid)
typedef ap_fixed<6, 1, AP_RND_CONV, AP_SAT> w1_gen_t;  // 2->2 weights (signed): scale=2^-5 (3.125000000e-02), bits=6, k=5
typedef ap_fixed<6, 2, AP_RND_CONV, AP_SAT> w2_gen_t;  // 2->0 weights (signed): scale=2^-4 (6.250000000e-02), bits=6, k=4

// ---- Raw-momentum / IO interface type (input_t): operand of the dot4
//      multipliers. TRAINED grid (Phase A*): pmu_quant = QuantIdentity on Pmu
//      before dot4, learned po2 scale. PyTorch and firmware grid the momenta
//      identically, so dots are bit-exact by construction (no analytic bound,
//      no Lever-2 cap). Leading |p| above the clip point saturates BY DESIGN;
//      the model was trained through that clipping.
//      Guard macro lets nPELICAN.h keep a hand fallback for the float path.
#define NPELICAN_INPUT_T_GENERATED 1
typedef ap_fixed<12, 12, AP_RND_CONV, AP_SAT> input_t;  // raw momenta; TRAINED pmu_quant grid (I=12, F=0); |p|max=2707.2

// ---- Float-trained biases / BatchNorm constants / normalization constants ----
// These are NOT PyTorch quantization points (PyTorch keeps them in float), so
// per CLAUDE.md/plan they are WIDENED, not snapped: their fixed-point rounding
// error must stay below half the LSB of the next real quantizer they feed.
typedef ap_fixed<16, 2, AP_RND_CONV, AP_SAT> bias1_t_gen;  // b1,b1_diag (float): F = mac2 grid w1_F+t2_F + G = 14 (G=8 guard bits); |b|max I=2
typedef ap_fixed<19, 2, AP_RND_CONV, AP_SAT> bias2_t_gen;  // b2 (float): F = mac0 grid w2_F+t0_F + G = 17 (G=8 guard bits); |b|max I=2
typedef bias1_t_gen bias_t_gen;  // legacy alias (single bias type, pre-2026-10-06)
typedef ap_fixed<21, 6, AP_RND_CONV, AP_SAT> bn_t_gen;  // BN mean/scale/beta (float); |c|max=27.0597 (I=6), F=15
typedef ap_fixed<24, 1, AP_RND_CONV, AP_SAT> norm_t;  // 1/N̄, 1/N̄^2 normalize-late multipliers (F=23)

// ---- Aggregation summands (unquantized BatchNorm outputs) + their accumulators.
//      AGG_F = 14 fractional bits (> the finest post-agg grid t0_F=5) so the
//      raw-sum-then-renormalize lands bit-exactly on the post-agg quantizer grid;
//      storing these on the coarse post-agg grid (e.g. t2_F) would tip the rounding.
//      Each is range-typed by its OWN BN output bound; SAT guards it. Accumulators
//      add ceil(log2(#terms)) integer headroom (H2=9 full sum, H1=5 row/trace).
typedef ap_fixed<20, 6, AP_RND_CONV, AP_SAT> bn1out_t;  // batch1 = BN1(dots); |batch1|<=29.6 (I=6), F=14
typedef ap_fixed<29, 15> acc2_t;     // jmass raw sum of bn1out_t (I(bn1out)+H2)
typedef ap_fixed<25, 11> accrow_t;   // jdotp row sums of bn1out_t (I(bn1out)+H1)
typedef ap_fixed<22, 8, AP_RND_CONV, AP_SAT> tr_t;  // Tr = BN2(relu); |Tr|<=88.7 (I=8); dump-only after #2 (BN2 folded past the 2->0 aggregation)
typedef ap_fixed<15, 13> accrelu_t;     // R full sum of relu_t Tp_q (I(relu)+H2)
typedef ap_fixed<11, 9> accrelurow_t;  // R trace, sum of relu_t Tp_q (I(relu)+H1)

// ---- MAC temporaries: I = I(weight)+I(operand)+ceil(log2(#terms)), W = I+B ----
typedef ap_fixed<15, 9> mac2_t;     // 2->2 dense: 6 w1*t2 products + b1 + b1_diag = 8 terms
// bias add for the 2->2 dense output: products accumulate in mac2_t (exact product grid);
// the float-typed bias is added ONCE here at full bias precision, then the relu quantizer rounds
#define NPELICAN_MAC2B_T_GENERATED 1
typedef ap_fixed<23, 9> mac2b_t;    // I = I(mac2_t), F = BIAS1_F = 14
typedef ap_fixed<23, 6> mac0_t;     // 2->0 dense: 2*NHIDDEN w2*t0 products + b2 = 5 terms; F = BIAS2_F = 17 (exact bias add)

#endif  // NPELICAN_TYPES_GENERATED_H_
