#ifndef NPELICAN_TYPES_FLOAT_H_
#define NPELICAN_TYPES_FLOAT_H_

// Float-reference build — included by nPELICAN.h when compiled with
// -DNPELICAN_FLOAT_BUILD (the equivariance harness's "float" model).
//
// Every datapath and weight typedef collapses to `double`, so the EXACT firmware
// algorithm (the same nPELICAN.cpp) runs with NO fixed-point quantization. This is
// the un-quantized Lorentz-invariance floor: under boosted beams the float-exact
// network is analytically invariant, so this build's residual drift is ~1e-13
// (machine epsilon), and ANY gap between a fixed-point curve and this one is 100%
// a quantization artifact — same code, only the number type changes.
//
// NOT touched here (and intentionally so): the ap_uint masks/counts in nPELICAN.cpp
// (nobjmask, ncount, ncount2) stay exact integers from ap_int.h. This header is a
// committed source file, NOT generated by model_loader.py (unlike types_generated.h).

// Satisfy nPELICAN.h's override guards so its ap_fixed fallbacks are all suppressed.
#define NPELICAN_GENERATED_TYPES 1
#define NPELICAN_INPUT_T_GENERATED 1
#define NPELICAN_RESULT_T_GENERATED 1
#define NPELICAN_LEGACY_WEIGHT_TYPES 1

// ---- Quantization-point + IO interface types ----
typedef double dot_t;       // input_quant (d_ij)
typedef double t2_t;        // post_agg 2->2
typedef double relu_t;      // act_layer (ReLU out)
typedef double t0_t;        // post_agg 2->0
typedef double out_t;       // output_quant
typedef double w1_gen_t;    // 2->2 weights
typedef double w2_gen_t;    // 2->0 weights
typedef double input_t;     // raw momenta / dot4 operands
typedef double result_t;    // final logit

// ---- Float-trained constant types (biases / BN / normalization) ----
typedef double bias_t_gen;
typedef double bn_t_gen;
typedef double norm_t;

// ---- Aggregation summands + their accumulators ----
typedef double bn1out_t;
typedef double acc2_t;
typedef double accrow_t;
typedef double tr_t;
typedef double accrelu_t;
typedef double accrelurow_t;

// ---- MAC temporaries ----
typedef double mac2_t;
typedef double mac0_t;

// ---- Legacy weight-array element types (the no-quant weights.h declares its
//      arrays with these: weight_t for w1/BN, bias_t for biases, internal_t for
//      the invnave normalization constants). ----
typedef double internal_t;
typedef double weight_t;
typedef double w1_t;
typedef double w2_t;
typedef double bias_t;

#endif  // NPELICAN_TYPES_FLOAT_H_
