#ifndef NPELICAN_TYPES_GENERATED_H_
#define NPELICAN_TYPES_GENERATED_H_

// GENERATED by model_loader.py --quant. Do not hand-edit.
// Per-quantizer fixed-point types derived from the checkpoint's learned
// Brevitas scales (k = -log2(scale); I = bits - k). Accumulator / MAC types
// derived by formula from those + term counts. Phase 1: INERT include — not
// yet wired into the datapath (Phase 2 swaps usage and retires the old types).

#include "ap_fixed.h"

#define NPELICAN_GENERATED_TYPES 1

// ---- Quantization-point types: ap_fixed<B, B-k, AP_RND_CONV, AP_SAT> ----
typedef ap_fixed<24, 14, AP_RND_CONV, AP_SAT> dot_t;  // input_quant (signed): scale=2^-10 (9.765625000e-04), bits=24, k=10
typedef ap_fixed<24, 6, AP_RND_CONV, AP_SAT> t2_t;  // post_agg 2->2 (signed): scale=2^-18 (3.814697266e-06), bits=24, k=18
typedef ap_fixed<24, 2, AP_RND_CONV, AP_SAT> relu_t;  // act_layer (QuantReLU) (signed): scale=2^-22 (2.384185791e-07), bits=24, k=22
typedef ap_fixed<24, 1, AP_RND_CONV, AP_SAT> t0_t;  // post_agg 2->0 (signed): scale=2^-23 (1.192092896e-07), bits=24, k=23
typedef ap_fixed<24, 1, AP_RND_CONV, AP_SAT> out_t;  // output_quant (signed): scale=2^-23 (1.192092896e-07), bits=24, k=23
typedef ap_fixed<24, 2, AP_RND_CONV, AP_SAT> w1_gen_t;  // 2->2 weights (signed): scale=2^-22 (2.384185791e-07), bits=24, k=22
typedef ap_fixed<24, 3, AP_RND_CONV, AP_SAT> w2_gen_t;  // 2->0 weights (signed): scale=2^-21 (4.768371582e-07), bits=24, k=21

// ---- Float-trained biases / BatchNorm constants / normalization constants ----
// These are NOT PyTorch quantization points (PyTorch keeps them in float), so
// per CLAUDE.md/plan they are WIDENED, not snapped: their fixed-point rounding
// error must stay below half the LSB of the next real quantizer they feed.
typedef ap_fixed<28, 4, AP_RND_CONV, AP_SAT> bias_t_gen;  // b1,b1_diag,b2 (float); |bias|max=0.339796<8 (I=4); F=24, err<=2^-25
typedef ap_fixed<40, 9, AP_RND_CONV, AP_SAT> bn_t_gen;  // BN mean/scale/beta (float); |c|max=126.495<2^8 (I=9); F=31
typedef ap_fixed<40, 1, AP_RND_CONV, AP_SAT> norm_t;  // 1/N̄, 1/N̄^2 normalize-late multipliers (F=39)

// ---- Aggregation summands (unquantized BatchNorm outputs) + their accumulators.
//      AGG_F = 24 fractional bits (> the finest post-agg grid t0_F=23) so the
//      raw-sum-then-renormalize lands bit-exactly on the post-agg quantizer grid;
//      storing these on the coarse post-agg grid (e.g. t2_F) would tip the rounding.
//      Each is range-typed by its OWN BN output bound; SAT guards it. Accumulators
//      add ceil(log2(#terms)) integer headroom (H2=9 full sum, H1=5 row/trace).
typedef ap_fixed<30, 6, AP_RND_CONV, AP_SAT> bn1out_t;  // batch1 = BN1(dots); |batch1|<=27.4 (I=6), F=24
typedef ap_fixed<39, 15> acc2_t;     // jmass raw sum of bn1out_t (I(bn1out)+H2)
typedef ap_fixed<35, 11> accrow_t;   // jdotp row sums of bn1out_t (I(bn1out)+H1)
typedef ap_fixed<33, 9, AP_RND_CONV, AP_SAT> tr_t;  // Tr = BN2(relu); |Tr|<=255.2 (I=9, vs t0_t I=1 which would saturate), F=24
typedef ap_fixed<42, 18> acc0_t;     // R full sum of tr_t (I(tr_t)+H2)
typedef ap_fixed<38, 14> acc0row_t;  // trace, sum of tr_t (I(tr_t)+H1)

// ---- MAC temporaries: I = I(weight)+I(operand)+ceil(log2(#terms)), W = I+B ----
typedef ap_fixed<51, 11> mac2_t;     // 2->2 dense: 6 w1*t2 products + b1 + b1_diag = 8 terms
typedef ap_fixed<51, 7> mac0_t;     // 2->0 dense: 2*NHIDDEN w2*t0 products + b2 = 5 terms

#endif  // NPELICAN_TYPES_GENERATED_H_
