#ifndef NPELICAN_TYPES_GENERATED_H_
#define NPELICAN_TYPES_GENERATED_H_

// GENERATED by model_loader.py --quant. Do not hand-edit.
// Per-quantizer fixed-point types derived from the checkpoint's learned
// Brevitas scales (k = -log2(scale); I = bits - k). Accumulator / MAC types
// derived by formula from those + term counts. Phase 1: INERT include — not
// yet wired into the datapath (Phase 2 swaps usage and retires the old types).

#include "ap_fixed.h"

#define NPELICAN_GENERATED_TYPES 1

// ---- Quantization-point types: ap_fixed<B, B-k, AP_RND_CONV, AP_SAT> ----
typedef ap_fixed<24, 14, AP_RND_CONV, AP_SAT> dot_t;  // input_quant (signed): scale=2^-10 (9.765625000e-04), bits=24, k=10
typedef ap_fixed<24, 6, AP_RND_CONV, AP_SAT> t2_t;  // post_agg 2->2 (signed): scale=2^-18 (3.814697266e-06), bits=24, k=18
typedef ap_fixed<24, 2, AP_RND_CONV, AP_SAT> relu_t;  // act_layer (QuantReLU) (signed): scale=2^-22 (2.384185791e-07), bits=24, k=22
typedef ap_fixed<24, 1, AP_RND_CONV, AP_SAT> t0_t;  // post_agg 2->0 (signed): scale=2^-23 (1.192092896e-07), bits=24, k=23
typedef ap_fixed<24, 1, AP_RND_CONV, AP_SAT> out_t;  // output_quant (signed): scale=2^-23 (1.192092896e-07), bits=24, k=23
typedef ap_fixed<24, 2, AP_RND_CONV, AP_SAT> w1_gen_t;  // 2->2 weights (signed): scale=2^-22 (2.384185791e-07), bits=24, k=22
typedef ap_fixed<24, 3, AP_RND_CONV, AP_SAT> w2_gen_t;  // 2->0 weights (signed): scale=2^-21 (4.768371582e-07), bits=24, k=21

// ---- Float-trained biases and BatchNorm constants ----
typedef ap_fixed<24, 4, AP_RND_CONV, AP_SAT> bias_t_gen;  // b1, b1_diag, b2 (float-trained); asserted max|bias|=0.339796 < 8
typedef ap_fixed<24, 12, AP_TRN_ZERO, AP_SAT> bn_t_gen;  // BN constants (mean O(100)); asserted max|c|=130.191 < 2^11

// ---- Accumulators (normalize-late: raw sum first, ONE rescale after; see
//      CLAUDE.md). Default ap_fixed rounding/overflow ON PURPOSE — accumulation
//      must be EXACT, so no AP_RND_CONV here; integer headroom = ceil(log2(#terms))
//      over the summand type. NPARTICLES2 = NPARTICLES+2 = 22.
//      H2 = ceil(log2(NPARTICLES2^2)) = 9; H1 = ceil(log2(NPARTICLES2)) = 5.
typedef ap_fixed<33, 15> acc2_t;     // jmass raw sum of t2-range summands (B+H2, I(t2_t)+H2)
typedef ap_fixed<29, 11> accrow_t;   // jdotp row sums (B+H1, I(t2_t)+H1)
typedef ap_fixed<33, 10> acc0_t;     // R full sum (B+H2, I(t0_t)+H2)
typedef ap_fixed<29, 6> acc0row_t;  // trace (B+H1, I(t0_t)+H1)

// ---- MAC temporaries: I = I(weight)+I(operand)+ceil(log2(#terms)), W = I+B ----
typedef ap_fixed<35, 11> mac2_t;     // 2->2 dense: 6 w1*t2 products + b1 + b1_diag = 8 terms
typedef ap_fixed<31, 7> mac0_t;     // 2->0 dense: 2*NHIDDEN w2*t0 products + b2 = 5 terms

#endif  // NPELICAN_TYPES_GENERATED_H_
